id = "kdl"
name = "kdl"
version = "0.0.1"
schema_version = 1
authors = ["ElKowar <dev@elkowar.dev>"]
description = "Syntax highlighting for KDL files."
repository = "https://github.com/elkowar/zed-kdl"

[grammars.kdl]
repository = "https://github.com/dector/tree-sitter-kdl2"
commit = "bb597f7a103a2aae0ef36e54113e1a867ec900e0"
